source 'https://rubygems.org'

# Fix Sinatra version to ensure compatibility with upcoming releases
gem 'sinatra', '1.4.7'

# Testing
gem 'rspec'
gem 'rack-test'

# Neography to connect to neo4j
gem 'neography', '1.8.0'

# Application
gem 'sinatra-flash', '0.3.0'
gem 'bcrypt', '3.1.11'
gem 'terminal-table', '1.7.3'

# CI 
gem "codeclimate-test-reporter", "~> 1.0.0"
